/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CaptureAllRouteImport } from './routes/capture-all'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaptureNameRouteImport } from './routes/capture.$name'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppStudentRouteImport } from './routes/_authenticated/app.student'
import { Route as AuthenticatedAppSendRouteImport } from './routes/_authenticated/app.send'
import { Route as AuthenticatedAppSanchayRouteImport } from './routes/_authenticated/app.sanchay'
import { Route as AuthenticatedAppQrRouteImport } from './routes/_authenticated/app.qr'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppPostpayRouteImport } from './routes/_authenticated/app.postpay'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppMissionsRouteImport } from './routes/_authenticated/app.missions'
import { Route as AuthenticatedAppKhamarRouteImport } from './routes/_authenticated/app.khamar'
import { Route as AuthenticatedAppGigRouteImport } from './routes/_authenticated/app.gig'
import { Route as AuthenticatedAppCashinRouteImport } from './routes/_authenticated/app.cashin'
import { Route as AuthenticatedAppBundlesRouteImport } from './routes/_authenticated/app.bundles'
import { Route as AuthenticatedAppBimaRouteImport } from './routes/_authenticated/app.bima'
import { Route as AuthenticatedAppBillsRouteImport } from './routes/_authenticated/app.bills'
import { Route as AuthenticatedAppBazaarRouteImport } from './routes/_authenticated/app.bazaar'
import { Route as AuthenticatedAppAiRouteImport } from './routes/_authenticated/app.ai'

const CaptureAllRoute = CaptureAllRouteImport.update({
  id: '/capture-all',
  path: '/capture-all',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureNameRoute = CaptureNameRouteImport.update({
  id: '/capture/$name',
  path: '/capture/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppStudentRoute = AuthenticatedAppStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSendRoute = AuthenticatedAppSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSanchayRoute = AuthenticatedAppSanchayRouteImport.update({
  id: '/sanchay',
  path: '/sanchay',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppQrRoute = AuthenticatedAppQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPostpayRoute = AuthenticatedAppPostpayRouteImport.update({
  id: '/postpay',
  path: '/postpay',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMissionsRoute =
  AuthenticatedAppMissionsRouteImport.update({
    id: '/missions',
    path: '/missions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppKhamarRoute = AuthenticatedAppKhamarRouteImport.update({
  id: '/khamar',
  path: '/khamar',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppGigRoute = AuthenticatedAppGigRouteImport.update({
  id: '/gig',
  path: '/gig',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCashinRoute = AuthenticatedAppCashinRouteImport.update({
  id: '/cashin',
  path: '/cashin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBundlesRoute = AuthenticatedAppBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBimaRoute = AuthenticatedAppBimaRouteImport.update({
  id: '/bima',
  path: '/bima',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBillsRoute = AuthenticatedAppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBazaarRoute = AuthenticatedAppBazaarRouteImport.update({
  id: '/bazaar',
  path: '/bazaar',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAiRoute = AuthenticatedAppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture-all': typeof CaptureAllRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/capture/$name': typeof CaptureNameRoute
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/bazaar': typeof AuthenticatedAppBazaarRoute
  '/app/bills': typeof AuthenticatedAppBillsRoute
  '/app/bima': typeof AuthenticatedAppBimaRoute
  '/app/bundles': typeof AuthenticatedAppBundlesRoute
  '/app/cashin': typeof AuthenticatedAppCashinRoute
  '/app/gig': typeof AuthenticatedAppGigRoute
  '/app/khamar': typeof AuthenticatedAppKhamarRoute
  '/app/missions': typeof AuthenticatedAppMissionsRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/postpay': typeof AuthenticatedAppPostpayRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/qr': typeof AuthenticatedAppQrRoute
  '/app/sanchay': typeof AuthenticatedAppSanchayRoute
  '/app/send': typeof AuthenticatedAppSendRoute
  '/app/student': typeof AuthenticatedAppStudentRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture-all': typeof CaptureAllRoute
  '/api/chat': typeof ApiChatRoute
  '/capture/$name': typeof CaptureNameRoute
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/bazaar': typeof AuthenticatedAppBazaarRoute
  '/app/bills': typeof AuthenticatedAppBillsRoute
  '/app/bima': typeof AuthenticatedAppBimaRoute
  '/app/bundles': typeof AuthenticatedAppBundlesRoute
  '/app/cashin': typeof AuthenticatedAppCashinRoute
  '/app/gig': typeof AuthenticatedAppGigRoute
  '/app/khamar': typeof AuthenticatedAppKhamarRoute
  '/app/missions': typeof AuthenticatedAppMissionsRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/postpay': typeof AuthenticatedAppPostpayRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/qr': typeof AuthenticatedAppQrRoute
  '/app/sanchay': typeof AuthenticatedAppSanchayRoute
  '/app/send': typeof AuthenticatedAppSendRoute
  '/app/student': typeof AuthenticatedAppStudentRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/capture-all': typeof CaptureAllRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/capture/$name': typeof CaptureNameRoute
  '/_authenticated/app/ai': typeof AuthenticatedAppAiRoute
  '/_authenticated/app/bazaar': typeof AuthenticatedAppBazaarRoute
  '/_authenticated/app/bills': typeof AuthenticatedAppBillsRoute
  '/_authenticated/app/bima': typeof AuthenticatedAppBimaRoute
  '/_authenticated/app/bundles': typeof AuthenticatedAppBundlesRoute
  '/_authenticated/app/cashin': typeof AuthenticatedAppCashinRoute
  '/_authenticated/app/gig': typeof AuthenticatedAppGigRoute
  '/_authenticated/app/khamar': typeof AuthenticatedAppKhamarRoute
  '/_authenticated/app/missions': typeof AuthenticatedAppMissionsRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/postpay': typeof AuthenticatedAppPostpayRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/qr': typeof AuthenticatedAppQrRoute
  '/_authenticated/app/sanchay': typeof AuthenticatedAppSanchayRoute
  '/_authenticated/app/send': typeof AuthenticatedAppSendRoute
  '/_authenticated/app/student': typeof AuthenticatedAppStudentRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture-all'
    | '/app'
    | '/api/chat'
    | '/capture/$name'
    | '/app/ai'
    | '/app/bazaar'
    | '/app/bills'
    | '/app/bima'
    | '/app/bundles'
    | '/app/cashin'
    | '/app/gig'
    | '/app/khamar'
    | '/app/missions'
    | '/app/notifications'
    | '/app/postpay'
    | '/app/profile'
    | '/app/qr'
    | '/app/sanchay'
    | '/app/send'
    | '/app/student'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture-all'
    | '/api/chat'
    | '/capture/$name'
    | '/app/ai'
    | '/app/bazaar'
    | '/app/bills'
    | '/app/bima'
    | '/app/bundles'
    | '/app/cashin'
    | '/app/gig'
    | '/app/khamar'
    | '/app/missions'
    | '/app/notifications'
    | '/app/postpay'
    | '/app/profile'
    | '/app/qr'
    | '/app/sanchay'
    | '/app/send'
    | '/app/student'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/capture-all'
    | '/_authenticated/app'
    | '/api/chat'
    | '/capture/$name'
    | '/_authenticated/app/ai'
    | '/_authenticated/app/bazaar'
    | '/_authenticated/app/bills'
    | '/_authenticated/app/bima'
    | '/_authenticated/app/bundles'
    | '/_authenticated/app/cashin'
    | '/_authenticated/app/gig'
    | '/_authenticated/app/khamar'
    | '/_authenticated/app/missions'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/postpay'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/qr'
    | '/_authenticated/app/sanchay'
    | '/_authenticated/app/send'
    | '/_authenticated/app/student'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CaptureAllRoute: typeof CaptureAllRoute
  ApiChatRoute: typeof ApiChatRoute
  CaptureNameRoute: typeof CaptureNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/capture-all': {
      id: '/capture-all'
      path: '/capture-all'
      fullPath: '/capture-all'
      preLoaderRoute: typeof CaptureAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/$name': {
      id: '/capture/$name'
      path: '/capture/$name'
      fullPath: '/capture/$name'
      preLoaderRoute: typeof CaptureNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/student': {
      id: '/_authenticated/app/student'
      path: '/student'
      fullPath: '/app/student'
      preLoaderRoute: typeof AuthenticatedAppStudentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/send': {
      id: '/_authenticated/app/send'
      path: '/send'
      fullPath: '/app/send'
      preLoaderRoute: typeof AuthenticatedAppSendRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sanchay': {
      id: '/_authenticated/app/sanchay'
      path: '/sanchay'
      fullPath: '/app/sanchay'
      preLoaderRoute: typeof AuthenticatedAppSanchayRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/qr': {
      id: '/_authenticated/app/qr'
      path: '/qr'
      fullPath: '/app/qr'
      preLoaderRoute: typeof AuthenticatedAppQrRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/postpay': {
      id: '/_authenticated/app/postpay'
      path: '/postpay'
      fullPath: '/app/postpay'
      preLoaderRoute: typeof AuthenticatedAppPostpayRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/missions': {
      id: '/_authenticated/app/missions'
      path: '/missions'
      fullPath: '/app/missions'
      preLoaderRoute: typeof AuthenticatedAppMissionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/khamar': {
      id: '/_authenticated/app/khamar'
      path: '/khamar'
      fullPath: '/app/khamar'
      preLoaderRoute: typeof AuthenticatedAppKhamarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/gig': {
      id: '/_authenticated/app/gig'
      path: '/gig'
      fullPath: '/app/gig'
      preLoaderRoute: typeof AuthenticatedAppGigRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cashin': {
      id: '/_authenticated/app/cashin'
      path: '/cashin'
      fullPath: '/app/cashin'
      preLoaderRoute: typeof AuthenticatedAppCashinRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bundles': {
      id: '/_authenticated/app/bundles'
      path: '/bundles'
      fullPath: '/app/bundles'
      preLoaderRoute: typeof AuthenticatedAppBundlesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bima': {
      id: '/_authenticated/app/bima'
      path: '/bima'
      fullPath: '/app/bima'
      preLoaderRoute: typeof AuthenticatedAppBimaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bills': {
      id: '/_authenticated/app/bills'
      path: '/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof AuthenticatedAppBillsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bazaar': {
      id: '/_authenticated/app/bazaar'
      path: '/bazaar'
      fullPath: '/app/bazaar'
      preLoaderRoute: typeof AuthenticatedAppBazaarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai': {
      id: '/_authenticated/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AuthenticatedAppAiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAiRoute: typeof AuthenticatedAppAiRoute
  AuthenticatedAppBazaarRoute: typeof AuthenticatedAppBazaarRoute
  AuthenticatedAppBillsRoute: typeof AuthenticatedAppBillsRoute
  AuthenticatedAppBimaRoute: typeof AuthenticatedAppBimaRoute
  AuthenticatedAppBundlesRoute: typeof AuthenticatedAppBundlesRoute
  AuthenticatedAppCashinRoute: typeof AuthenticatedAppCashinRoute
  AuthenticatedAppGigRoute: typeof AuthenticatedAppGigRoute
  AuthenticatedAppKhamarRoute: typeof AuthenticatedAppKhamarRoute
  AuthenticatedAppMissionsRoute: typeof AuthenticatedAppMissionsRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppPostpayRoute: typeof AuthenticatedAppPostpayRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppQrRoute: typeof AuthenticatedAppQrRoute
  AuthenticatedAppSanchayRoute: typeof AuthenticatedAppSanchayRoute
  AuthenticatedAppSendRoute: typeof AuthenticatedAppSendRoute
  AuthenticatedAppStudentRoute: typeof AuthenticatedAppStudentRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAiRoute: AuthenticatedAppAiRoute,
  AuthenticatedAppBazaarRoute: AuthenticatedAppBazaarRoute,
  AuthenticatedAppBillsRoute: AuthenticatedAppBillsRoute,
  AuthenticatedAppBimaRoute: AuthenticatedAppBimaRoute,
  AuthenticatedAppBundlesRoute: AuthenticatedAppBundlesRoute,
  AuthenticatedAppCashinRoute: AuthenticatedAppCashinRoute,
  AuthenticatedAppGigRoute: AuthenticatedAppGigRoute,
  AuthenticatedAppKhamarRoute: AuthenticatedAppKhamarRoute,
  AuthenticatedAppMissionsRoute: AuthenticatedAppMissionsRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppPostpayRoute: AuthenticatedAppPostpayRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppQrRoute: AuthenticatedAppQrRoute,
  AuthenticatedAppSanchayRoute: AuthenticatedAppSanchayRoute,
  AuthenticatedAppSendRoute: AuthenticatedAppSendRoute,
  AuthenticatedAppStudentRoute: AuthenticatedAppStudentRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CaptureAllRoute: CaptureAllRoute,
  ApiChatRoute: ApiChatRoute,
  CaptureNameRoute: CaptureNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
